services:
  rstudio:
    build:
      context: .
    ports:
      - 8787:8787
    environment:
      DISABLE_AUTH: true
    volumes:
      - .:/home/rstudio/workspace
      - r-lib:/usr/local/lib/R

volumes:
  r-lib:
