[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true

[font]
normal = { family = "Jetbrains Mono Nerd Font", style = "Regular" }
size = 13

[colors.primary]
foreground = "#D8DEE9"
background = "#2E3440"

[colors.cursor]
text   = "#282828"
cursor = "#ECEFF4"

[colors.selection]
text       = "#4C566A"
background = "#ECEFF4"

[colors.normal]
black   = "#3B4252"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#81A1C1"
magenta = "#B48EAD"
cyan    = "#88C0D0"
white   = "#E5E9F0"

[colors.bright]
black   = "#4C566A"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#81A1C1"
magenta = "#B48EAD"
cyan    = "#8FBCBB"
white   = "#ECEFF4"
